# Generated by Django 4.2.2 on 2023-07-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
