# Generated by Django 4.2.2 on 2023-07-31 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mensajecontacto_atendido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
