# Generated by Django 4.2.2 on 2023-07-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
