# Generated by Django 4.2.2 on 2023-07-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_app', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={},
        ),
    ]
