# Generated by Django 4.2.2 on 2023-07-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos_app', '0003_alter_publicacion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='contenido',
        ),
    ]
