# Generated by Django 4.2.2 on 2023-07-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_app', '0003_alter_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_admin',
        ),
    ]
