# Generated by Django 4.2.2 on 2023-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios_app', '0004_remove_usuario_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sobre_mi',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
